baseURL = 'https://eliyahu.co.uk/'
locale = 'en-gb'
title = 'Eliyahu Gluschove-Koppel'
theme = 'egkoppel'
buildDrafts = true

[markup]
  [markup.highlight]
    lineNos = true
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

[menus]
  [[menus.main]]
    name = "CV"
    weight = 10000000
    url = "/assets/cv_2026-07.0.pdf"

[taxonomies]
  series = 'series'
